version: '3.8'

services:
  symlink:
    build: .
    container_name: symlink
    volumes:
      # 配置文件
      - ./config:/app/config
      # 数据目录
      - ./data:/app/data
      # 挂载点
      - ${MOUNT_POINT:-/media/mount}:/media/mount:shared
      # 软链接目标目录
      - ${TARGET_BASE:-/media/links}:/media/links
      # 日志目录
      - ${LOG_PATH:-/var/log/symlink}:/var/log/symlink
    environment:
      - MOUNT_POINT=/media/mount
      - TARGET_BASE=/media/links
      - LOG_PATH=/var/log/symlink
      - DATABASE_PATH=/app/data/database.db
    ports:
      - "8501:8501"  # Streamlit Web UI
    restart: unless-stopped
    privileged: true  # 需要特权模式以支持软链接操作
    networks:
      - symlink_net

networks:
  symlink_net:
    driver: bridge 