version: '3.8'

services:
  symlink:
    build: .
    container_name: symlink
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ${RCLONE_CONFIG:-~/.config/rclone}:/root/.config/rclone
    environment:
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - EMBY_SERVER_URL=${EMBY_SERVER_URL}
      - EMBY_API_KEY=${EMBY_API_KEY}
      - API_CALL_INTERVAL=${API_CALL_INTERVAL:-3600}
      - POLLING_INTERVAL=${POLLING_INTERVAL:-300}
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    networks:
      - symlink_net

networks:
  symlink_net:
    driver: bridge 