version: '3.8'

services:
  symlink:
    image: gray777/symlink:latest
    container_name: symlink
    user: "0:0"
    volumes:
      # 配置文件
      - /root/link/config:/app/config:ro
      # 数据目录
      - /root/link/data:/app/data
      # 挂载点
      - /mnt/9w:/mnt/9w:shared
      # 软链接目标目录
      - /mnt/media:/mnt/media
      # 日志目录
      - /root/link/log:/var/log/symlink
      - /mnt:/mnt
    environment:
      - MOUNT_POINT=/mnt/9w
      - TARGET_BASE=/mnt/media
      - LOG_PATH=/var/log/symlink
      - DATABASE_PATH=/app/data/database.db
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
      - CONFIG_PATH=/app/config/config.yaml
    ports:
      - "8501:8501"  # Streamlit Web UI
      - "8000:8000"  # FastAPI
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN  # 需要此权限来支持 FUSE
    devices:
      - /dev/fuse:/dev/fuse  # 需要访问 FUSE 设备
    security_opt:
      - apparmor:unconfined  # 某些系统可能需要此选项来支持 FUSE
    privileged: true  # 需要特权模式以支持软链接操作
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - symlink_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      - net.core.somaxconn=1024

networks:
  symlink_net:
    driver: bridge 