version: '3.8'

services:
  symlink:
    build: .
    container_name: symlink
    volumes:
      # 配置文件
      - ./config:/app/config:ro
      # 数据目录
      - ./data:/app/data
      # 挂载点
      - ${MOUNT_POINT:-/media/mount}:/media/mount:shared
      # 软链接目标目录
      - ${TARGET_BASE:-/media/links}:/media/links
      # 日志目录
      - ${LOG_PATH:-/var/log/symlink}:/var/log/symlink
    environment:
      - MOUNT_POINT=/media/mount
      - TARGET_BASE=/media/links
      - LOG_PATH=/var/log/symlink
      - DATABASE_PATH=/app/data/database.db
      - TZ=Asia/Shanghai
    ports:
      - "8501:8501"  # Streamlit Web UI
      - "8000:8000"  # FastAPI
    restart: unless-stopped
    privileged: true  # 需要特权模式以支持软链接操作
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - symlink_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  symlink_net:
    driver: bridge 